# Numpy Boolean Indexing

In [1]:
import numpy as np

np.__version__

'1.17.4'

In [2]:
y = np.random.randint(-100, 100, 10)

y

array([-92,  17,  35,  79,  85,   3, -76, -16,  33,  55])

In [3]:
z = np.array([True, False]*5)

z

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [4]:
y[z]

array([-92,  35,  85, -76,  33])

In [5]:
x = np.random.randint(0, 1000, (5,5))

x

array([[854, 933, 110, 326, 752],
       [239, 568, 211, 539, 606],
       [237, 113, 804, 969, 720],
       [536,  26, 637, 917, 194],
       [434, 252,  30, 185, 424]])

In [6]:
x > 500

array([[ True,  True, False, False,  True],
       [False,  True, False,  True,  True],
       [False, False,  True,  True,  True],
       [ True, False,  True,  True, False],
       [False, False, False, False, False]])

In [7]:
x[ x > 500 ]

array([854, 933, 752, 568, 539, 606, 804, 969, 720, 536, 637, 917])

In [8]:
x[ ( x > 500) & (x < 700)]

array([568, 539, 606, 536, 637])

In [9]:
x[ (x < 100) | (x > 900)]

array([933, 969,  26, 917,  30])

#### Replacing Values

In [10]:
x

array([[854, 933, 110, 326, 752],
       [239, 568, 211, 539, 606],
       [237, 113, 804, 969, 720],
       [536,  26, 637, 917, 194],
       [434, 252,  30, 185, 424]])

In [11]:
x[ x < 500] = -1

In [12]:
x

array([[854, 933,  -1,  -1, 752],
       [ -1, 568,  -1, 539, 606],
       [ -1,  -1, 804, 969, 720],
       [536,  -1, 637, 917,  -1],
       [ -1,  -1,  -1,  -1,  -1]])