# Why Numpy?

Let's get on the same page first! Version Matching!

In [1]:
import sys

sys.version

'3.7.7 (default, Apr  1 2020, 13:48:52) \n[GCC 9.3.0]'

In [2]:
import numpy as np  # most devs like to use "np" 

np.__version__

'1.17.4'

### Simple Example using Lists

In [3]:
a = [1, 2, 9, 11, 12]
b = [-3, 2, 10, 12, 13]

#### Create a new array -  Multiply every element of "a" by 5

In [4]:
[x*5 for x in a]

[5, 10, 45, 55, 60]

Numpy Technique :)

In [5]:
a_numpy = np.array(a)

a_numpy

array([ 1,  2,  9, 11, 12])

In [6]:
5 * a_numpy

array([ 5, 10, 45, 55, 60])

#### Add 2 lists element by element

List technique

In [7]:
[sum(x) for x in zip(a,b)]

[-2, 4, 19, 23, 25]

Numpy Technique?

In [8]:
a_numpy = np.array(a)
b_numpy = np.array(b)

In [9]:
a_numpy + b_numpy

array([-2,  4, 19, 23, 25])

But is this so "easy" that we need to learn a new library?

#### Is Numpy faster? What if we have really large datasets?

In [19]:
large_a = [1,2]*10**7

len(large_a)

20000000

In [11]:
large_b = [2,3]*10**7

len(large_b)

20000000

##### Timing and Profiling  
Good Reference: http://pynash.org/2013/03/06/timing-and-profiling/

Let us see the time taken when adding these large lists using our regular technique

In [12]:
%time temp = [sum(x) for x in zip(large_a, large_b)]

CPU times: user 4.11 s, sys: 31.9 ms, total: 4.14 s
Wall time: 4.14 s


In [13]:
len(temp), temp[:10]

(20000000, [3, 5, 3, 5, 3, 5, 3, 5, 3, 5])

Now let's take Numpy out for a spin!

In [14]:
large_a_np = np.array(large_a)

large_b_np = np.array(large_b)

In [15]:
%time large_sum = large_a_np + large_b_np

CPU times: user 72.3 ms, sys: 20.3 ms, total: 92.6 ms
Wall time: 90.5 ms


In [16]:
len(large_sum), large_sum[:10]

(20000000, array([3, 5, 3, 5, 3, 5, 3, 5, 3, 5]))

### Numpy clearly shows an ROI when we are working with Large Datasets